### ISSUE TITLE
error initializing the Custom Card

### ISSUE THREAD

**Issue by bsp9493** [petergridge/irrigation_card#1]
Hi Peter…

I get the following error when home assistant tries to initialize the the Custom Card for irrigation_component on startup.  What am I missing?

Logger: frontend.js.latest.202111030
Source: components/system_log/__init__.py:190 
First occurred: 9:23:03 AM (1 occurrences) 
Last logged: 9:23:03 AM

http://homeassistant.local:8123/local/irrigation-card.js:25:53 Error: switch.afternoon not found

the rest of the upgrade to v4 is all good:)

Thanx

dave

**Comment by petergridge** [comment]
Hi Dave,

A couple of things to debug the card, sorry some back to basics questions:
1. can you confirm that switch.afternoon is defined for you irrigation config.
2.Can you send me an extract of the raw lovelace yaml that has the card definition.
![image](https://user-images.githubusercontent.com/40281772/140811793-44cf38ab-eaa9-4109-986d-c51e77ff9d1c.png)

I have had look and the error handling is not the best so I will try to improve on this.

**Comment by bsp9493** [comment]
Hi Peter…

Please see my current setup (this is what I set up from previous version(s).  I did not use your default,  (I used it as a guide to create my own) so I do NOT have “afternoon.switch”


views:
  - title: Irrigation
    path: irrigation
    badges: []
    cards:
      - type: entities
        entities:
          - entity: input_boolean.irrigation_config
          - entity: binary_sensor.raining
          - entity: sensor.soil_moisture_level
          - conditions:
              - entity: input_boolean.irrigation_config
                state: 'on'
            row:
              entity: input_boolean.irrigation_on
            type: conditional
          - conditions:
              - entity: input_boolean.irrigation_config
                state: 'on'
            row:
              entity: input_boolean.irrigation_ignore_rain_sensor
            type: conditional
          - conditions:
              - entity: input_boolean.irrigation_config
                state: 'on'
            row:
              entity: input_number.irrigation_adjust_run
            type: conditional
        show_header_toggle: false
        title: Irrigation
        state_color: true
      - type: entities
        entities:
          - type: section
            label: program_1
          - entity: switch.program_1
          - entity: switch.program_1
            type: attribute
            attribute: last_ran
            name: Last Run
          - conditions:
              - entity: switch.program_1
                state: 'on'
            row:
              type: attribute
              entity: switch.program_1
              attribute: remaining
            type: conditional
          - conditions:
              - entity: input_boolean.irrigation_config
                state: 'on'
            row:
              entity: input_datetime.irrigation_program_1_start_time
            type: conditional
          - conditions:
              - entity: input_boolean.irrigation_config
                state: 'on'
            row:
              entity: input_select.irrigation_run_days
            type: conditional
          - type: section
            label: program_2
          - entity: switch.program_2
          - entity: switch.program_2
            type: attribute
            attribute: last_ran
            name: Last Run
          - conditions:
              - entity: switch.program_2
                state: 'on'
            row:
              type: attribute
              entity: switch.program_2
              attribute: remaining
            type: conditional
          - conditions:
              - entity: input_boolean.irrigation_config
                state: 'on'
            row:
              entity: input_datetime.irrigation_program_2_start_time
            type: conditional
          - conditions:
              - entity: input_boolean.irrigation_config
                state: 'on'
            row:
              entity: input_select.irrigation_run_days
            type: conditional
          - type: section
            label: program_3
          - entity: switch.program_3
          - entity: switch.program_3
            type: attribute
            attribute: last_ran
            name: Last Run
          - conditions:
              - entity: switch.program_3
                state: 'on'
            row:
              type: attribute
              entity: switch.program_3
              attribute: remaining
            type: conditional
          - conditions:
              - entity: input_boolean.irrigation_config
                state: 'on'
            row:
              entity: input_datetime.irrigation_program_3_start_time
            type: conditional
          - conditions:
              - entity: input_boolean.irrigation_config
                state: 'on'
            row:
              entity: input_select.irrigation_run_days
            type: conditional
        title: Programs
        show_header_toggle: false
        state_color: true
      - type: conditional
        conditions:
          - entity: input_boolean.irrigation_config
            state: 'on'
        card:
          type: entities
          entities:
            - type: section
              label: Front Lawn
            - entity: input_number.irrigation_front_lawn_run
            - entity: input_number.irrigation_front_lawn_wait
            - entity: input_number.irrigation_front_lawn_repeat
            - type: section
              label: Front Door Shrubs
            - entity: input_number.irrigation_front_door_shrubs_run
            - entity: input_number.irrigation_front_door_shrubs_wait
            - entity: input_number.irrigation_front_door_shrubs_repeat
            - type: section
              label: Front Street
            - entity: input_number.irrigation_front_street_run
            - entity: input_number.irrigation_front_street_wait
            - entity: input_number.irrigation_front_street_repeat
            - type: section
              label: Back Dripline
            - entity: input_number.irrigation_back_dripline_run
            - entity: input_number.irrigation_back_dripline_wait
            - entity: input_number.irrigation_back_dripline_repeat
          title: Zone
      - type: conditional
        conditions:
          - entity: input_boolean.irrigation_config
            state: 'on'
        card:
          type: entities
          entities:
            - entity: switch.front_lawn_zone
            - entity: switch.front_door_shrubs_zone
            - entity: switch.front_street_zone
            - entity: switch.back_dripline_zone
          title: Solenoids
          show_header_toggle: false
          state_color: true
  - title: bhyve
    badges: []
    cards:
      - type: entities
        entities:
          - entity: switch.back_dripline_zone
          - entity: switch.front_door_shrubs_zone
          - entity: switch.front_lawn_zone
          - entity: switch.front_street_zone
          - entity: switch.do_not_use_zone
      - type: entities
        entities:
          - entity: switch.bdm_home_back_trees_program
          - entity: switch.bdm_home_manual_x4_program
          - entity: switch.bdm_home_rain_delay
          - entity: sensor.bdm_home_state
          - entity: sensor.meteobridge_rain_today
      - type: entities
        entities:
          - entity: sensor.back_dripline_zone_history
          - entity: sensor.do_not_use_zone_history
          - entity: sensor.front_door_shrubs_zone_history
          - entity: sensor.front_lawn_zone_history
          - entity: sensor.front_street_zone_history
title: Irrigation




Having said that… V4 works fine with my existing setup.  I just thought I would try to implement the custom card you created and see what it looks like and how it functions.

When I go through the “normal” steps to add the .js resource for the custom card all is fine.  Where the error comes is after this step on reboot.

steps and expected outcome below

copy .js file to config/www directory
add lovelace resource as normal as you note
reboot server so it loads the new card type.

go to my irrigation tab, click edit, try to add “NEW” card. (I would expect the custom card to be available for selection like other’s that I have added.
	card does NOT exist
	try to add card manually
		card does NOT exist

check error logs to see what happened.

based on the logs, I’m guessing there is something going on when homeassistant restarts and tries to define/make available the custom card type.
 

I hope this helps to explain better.


Thanx again for the great implementation!!!


I have also included my irrigation.yaml for reference.  NOTE: I am using packages to set up my individual .yaml files so the spacing/indentation may NOT look as you expect:)


irrigation:
#    input_datetime:
#      irrigation_program_1_start_time:
#        name: Start Time 1
#        has_date: false
#        has_time: true
#      irrigation_program_2_start_time:
#        name: Start Time 2
#        has_date: false
#        has_time: true
#      irrigation_program_3_start_time:
#        name: Start Time 3
#        has_date: false
#        has_time: true
    switch:
      - platform: irrigationprogram
        switches: 
          program_1:
            irrigation_on: input_boolean.irrigation_on
            start_time: input_datetime.irrigation_program_1_start_time
            run_freq: input_select.irrigation_run_freq
            icon: mdi:fountain
            zones:
              - zone: switch.dummy_1
                name:  Front Lawn
                water: input_number.irrigation_front_lawn_run
                water_adjustment: input_number.irrigation_adjust_run
                wait: input_number.irrigation_front_lawn_wait
                repeat: input_number.irrigation_front_lawn_repeat
                rain_sensor: binary_sensor.meteobridge_is_raining
                ignore_rain_sensor: input_boolean.irrigation_ignore_rain_sensor
                icon: mdi:grass
              - zone: switch.dummy_2
                name:  Front Door Shrubs
                water: input_number.irrigation_front_door_shrubs_run
                water_adjustment: input_number.irrigation_adjust_run
                wait: input_number.irrigation_front_door_shrubs_wait
                repeat: input_number.irrigation_front_door_shrubs_repeat
                rain_sensor: binary_sensor.meteobridge_is_raining
                ignore_rain_sensor: input_boolean.irrigation_ignore_rain_sensor
                icon: mdi:grass
              - zone: switch.dummy_3
                name:  Front Street
                water: input_number.irrigation_front_street_run
                water_adjustment: input_number.irrigation_adjust_run          
                wait: input_number.irrigation_front_street_wait
                repeat: input_number.irrigation_front_street_repeat
                rain_sensor: binary_sensor.meteobridge_is_raining
                ignore_rain_sensor: input_boolean.irrigation_ignore_rain_sensor
                icon: mdi:grass
              - zone: switch.dummy_5
                name:  Back Dripline
                water: input_number.irrigation_back_dripline_run
                water_adjustment: input_number.irrigation_adjust_run
                wait: input_number.irrigation_back_dripline_wait
                repeat: input_number.irrigation_back_dripline_repeat
                rain_sensor: binary_sensor.meteobridge_is_raining
                ignore_rain_sensor: input_boolean.irrigation_ignore_rain_sensor
                icon: mdi:grass
          program_2:
            irrigation_on: input_boolean.irrigation_on
            start_time: input_datetime.irrigation_program_2_start_time
            run_freq: input_select.irrigation_freq
            icon: mdi:fountain
            zones:
              - zone: switch.dummy_1
                name:  Front Lawn
                water: input_number.irrigation_front_lawn_run
                water_adjustment: input_number.irrigation_adjust_run
                wait: input_number.irrigation_front_lawn_wait
                repeat: input_number.irrigation_front_lawn_repeat
                rain_sensor: binary_sensor.meteobridge_is_raining
                ignore_rain_sensor: input_boolean.irrigation_ignore_rain_sensor
                icon: mdi:grass
              - zone: switch.dummy_2
                name:  Front Door Shrubs
                water: input_number.irrigation_front_door_shrubs_run
                water_adjustment: input_number.irrigation_adjust_run
                wait: input_number.irrigation_front_door_shrubs_wait
                repeat: input_number.irrigation_front_door_shrubs_repeat
                rain_sensor: binary_sensor.meteobridge_is_raining
                ignore_rain_sensor: input_boolean.irrigation_ignore_rain_sensor
                icon: mdi:grass
              - zone: switch.dummy_3
                name:  Front Street
                water: input_number.irrigation_front_street_run
                water_adjustment: input_number.irrigation_adjust_run
                wait: input_number.irrigation_front_street_wait
                repeat: input_number.irrigation_front_street_repeat
                rain_sensor: binary_sensor.meteobridge_is_raining
                ignore_rain_sensor: input_boolean.irrigation_ignore_rain_sensor
                icon: mdi:grass
              - zone: switch.dummy_5
                name:  Back Dripline
                water: input_number.irrigation_back_dripline_run
                water_adjustment: input_number.irrigation_adjust_run
                wait: input_number.irrigation_back_dripline_wait
                repeat: input_number.irrigation_back_dripline_repeat
                rain_sensor: binary_sensor.meteobridge_is_raining
                ignore_rain_sensor: input_boolean.irrigation_ignore_rain_sensor
                icon: mdi:grass
                
          program_3:
            irrigation_on: input_boolean.irrigation_on
            start_time: input_datetime.irrigation_program_3_start_time
            run_freq: input_select.irrigation_freq
            icon: mdi:fountain
            zones:
              - zone: switch.dummy_1
                name:  Front Lawn
                water: input_number.irrigation_front_lawn_run
                water_adjustment: input_number.irrigation_adjust_run
                wait: input_number.irrigation_front_lawn_wait
                repeat: input_number.irrigation_front_lawn_repeat
                rain_sensor: binary_sensor.meteobridge_is_raining
                ignore_rain_sensor: input_boolean.irrigation_ignore_rain_sensor
                icon: mdi:grass
              - zone: switch.dummy_2
                name:  Front Door Shrubs
                water: input_number.irrigation_front_door_shrubs_run
                water_adjustment: input_number.irrigation_adjust_run
                wait: input_number.irrigation_front_door_shrubs_wait
                repeat: input_number.irrigation_front_door_shrubs_repeat
                rain_sensor: binary_sensor.meteobridge_is_raining
                ignore_rain_sensor: input_boolean.irrigation_ignore_rain_sensor
                icon: mdi:grass
              - zone: switch.dummy_3
                name:  Front Street
                water: input_number.irrigation_front_street_run
                water_adjustment: input_number.irrigation_adjust_run
                wait: input_number.irrigation_front_street_wait
                repeat: input_number.irrigation_front_street_repeat
                rain_sensor: binary_sensor.meteobridge_is_raining
                ignore_rain_sensor: input_boolean.irrigation_ignore_rain_sensor
                icon: mdi:grass
              - zone: switch.dummy_5
                name:  Back Dripline
                water: input_number.irrigation_back_dripline_run
                water_adjustment: input_number.irrigation_adjust_run
                wait: input_number.irrigation_back_dripline_wait
                repeat: input_number.irrigation_back_dripline_repeat
                rain_sensor: binary_sensor.meteobridge_is_raining
                ignore_rain_sensor: input_boolean.irrigation_ignore_rain_sensor
                icon: mdi:grass
      - platform: template
        switches:
          dummy_1:
            value_template: "{{ is_state('switch.front_lawn_zone', 'on') }}"
            turn_on:
              service: bhyve.start_watering
              data:
                entity_id: switch.front_lawn_zone
                #max minutes to run
                minutes: 60
            turn_off:
              service: bhyve.stop_watering
              data:
                entity_id: switch.front_lawn_zone

          dummy_2:
            value_template: "{{ is_state('switch.front_door_shrubs_zone', 'on') }}"
            turn_on:
              service: bhyve.start_watering
              data:
                entity_id: switch.front_door_shrubs_zone
                #max minutes to run
                minutes: 60
            turn_off:
              service: bhyve.stop_watering
              data:
                entity_id: switch.front_door_shrubs_zone

          dummy_3:
            value_template: "{{ is_state('switch.front_street_zone', 'on') }}"
            turn_on:
              service: bhyve.start_watering
              data:
                entity_id: switch.front_street_zone
                #max minutes to run
                minutes: 60
            turn_off:
              service: bhyve.stop_watering
              data:
                entity_id: switch.front_street_zone
                
          dummy_5:
            value_template: "{{ is_state('switch.back_dripline_zone', 'on') }}"
            turn_on:
              service: bhyve.start_watering
              data:
                entity_id: switch.back_dripline_zone
                #max minutes to run
                minutes: 60
            turn_off:
              service: bhyve.stop_watering
              data:
                entity_id: switch.back_dripline_zone


    input_number:
# seasonal adjustment
      irrigation_adjust_run:
        name: water adjustment
        min: 0
        max: 1
        step: 0.05
        icon: mdi:water-pump-off
#front lawn
      irrigation_front_lawn_run:
        name: water
        min: 1
        max: 20
        step: 1
        icon: mdi:water
      irrigation_front_lawn_wait:
        name: wait
        min: 0
        max: 10
        step: 1
        icon: mdi:timer-sand
      irrigation_front_lawn_repeat:
        name: repeat
        min: 0
        max: 10
        step: 1
        icon: mdi:repeat
#front door shrubs
      irrigation_front_door_shrubs_run:
        name: water
        min: 1
        max: 20
        step: 1
        icon: mdi:water
      irrigation_front_door_shrubs_wait:
        name: wait
        min: 0
        max: 10
        step: 1
        icon: mdi:timer-sand
      irrigation_front_door_shrubs_repeat:
        name: repeat
        min: 0
        max: 10
        step: 1
        icon: mdi:repeat
#front street
      irrigation_front_street_run:
        name: water
        min: 1
        max: 20
        step: 1
        icon: mdi:water
      irrigation_front_street_wait:
        name: wait
        min: 0
        max: 10
        step: 1
        icon: mdi:timer-sand
      irrigation_front_street_repeat:
        name: repeat
        min: 0
        max: 10
        step: 1
        icon: mdi:repeat
#back dripline
      irrigation_back_dripline_run:
        name: water
        min: 1
        max: 60
        step: 1
        icon: mdi:water
      irrigation_back_dripline_wait:
        name: wait
        min: 0
        max: 10
        step: 1
        icon: mdi:timer-sand
      irrigation_back_dripline_repeat:
        name: repeat
        min: 0
        max: 10
        step: 1
        icon: mdi:repeat

    input_select:
    # Use either run days of Frequency they are mutually exclusive
# deprecated in version 4
#      irrigation_run_freqs:
#        name: Run Days
#        options:
#          - "['Wed','Sat']"
#          - "['Sun','Thu']"
#          - "['Mon','Fri']"
#          - "['Tue','Sat']"
#          - "['Sun','Wed']"
#          - "['Mon','Thu']"
#          - "['Tue','Fri']"
#          - "['Mon','Wed','Fri']"
#          - "['Mon','Tue','Wed','Thu','Fri','Sat','Sun']"
#          - "['Sun','Wed','Fri']"

      irrigation_freq:
        name: Frequency
        options:
          - "1"
          - "2"
          - "3"
          - "4"
          - "5"
          - "6"
          - "7"
          - "['Wed','Sat']"
          - "['Sun','Thu']"
          - "['Mon','Fri']"
          - "['Tue','Sat']"
          - "['Sun','Wed']"
          - "['Mon','Thu']"
          - "['Tue','Fri']"
          - "['Mon','Wed','Fri']"
          - "['Mon','Tue','Wed','Thu','Fri','Sat','Sun']"
          - "['Sun','Wed','Fri']"


    input_boolean:
      irrigation_on:
        name: Enable Irrigation

      irrigation_config:
        name: Show Configuration

      irrigation_ignore_rain_sensor:
        name: Ignore Rain Sensor
  
      dummy_switch_1:
      dummy_switch_2:
      dummy_switch_3:
      dummy_switch_5:
      dummy_rain_sensor:

    binary_sensor:
      - platform: template
        sensors:
          raining:
            device_class: moisture
            value_template: "{{ is_state('binary_sensor.meteobridge_is_raining', 'on') }}"
            icon_template: >-
              {% if is_state("binary_sensor.meteobridge_is_raining", "on") %}
                mdi:weather-pouring
              {% else %}
                mdi:weather-sunny
              {% endif %}




d

**Comment by bsp9493** [comment]
Ahhh… looks like a misunderstanding on my part how the CARD works.


did some more playing, setup a MANUAL card as you have noted, changed my switch to switch.program_1 and voila… it creates a new pretty card:)

Sorry for the confusion on my  part:(

d

**Comment by petergridge** [comment]
That's good news. One good thing from this is it has prompted me to understand the error handling better.
I will be putting up a new version of the card that is a little more robust but by no means perfect shortly. I let you know when I am done, with some instructions.

BTW, where are you?

**Comment by bsp9493** [comment]
I think the custom Card will be very helpful for new implementations!  Manually setting up the yaml for the card implementation was initially the hardest part for me.  Great work!


Kelowna BC Canada

**Comment by petergridge** [comment]
Issue resolved
